= Setting up for development work

- You will need Ruby version specified in `./.ruby-version` in your development environment.
- Clone this repo
- `cd` into this repo
- Do `bundle install` -- this will install other dependencies

That should be it!

To test, do `rake spec`. This command runs all the automated RSpec tests. If everything's good, you'll see something like:

..................................................
/Users/kristina/.rvm/rubies/ruby-2.6.6/bin/ruby -I/Users/kristina/.rvm/gems/ruby-2.6.6/gems/rspec-core-3.9.2/lib:/Users/kristina/.rvm/gems/ruby-2.6.6/gems/rspec-support-3.9.3/lib /Users/kristina/.rvm/gems/ruby-2.6.6/gems/rspec-core-3.9.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

CollectionSpace::Mapper::DataHandler
  #validate
    returns Mapper::Response object
  #map
    returns Mapper::Response object
    the Mapper::Response object doc attribute is a Nokogiri XML Document
  #merge_config_transforms
    anthro_4_0_0 profile
      collectionobject record type
        collection data field
          merges data field specific transforms
..................................................

...and it will go on for several screens.
