# frozen_string_literal: true

module Helpers

  def anthro_client
    CollectionSpace::Client.new(
      CollectionSpace::Configuration.new(
        base_uri: 'https://anthro.dev.collectionspace.org/cspace-services',
        username: 'admin@anthro.collectionspace.org',
        password: 'Administrator'
      )
    )
  end
  memo_wise(:anthro_client)

  def anthro_cache
    cache_config = base_cache_config.merge({domain: anthro_client.domain})
    cache = CollectionSpace::RefCache.new(config: cache_config)
    populate_anthro(cache)
    cache
  end
  memo_wise(:anthro_cache)

  def anthro_object_mapper
    path = 'spec/fixtures/files/mappers/release_6_1/anthro/anthro_4-1-2_collectionobject.json'
    get_record_mapper_object(path)
  end

  def populate_anthro(cache)
    terms = [
      ['conceptauthorities', 'archculture', 'Blackfoot',
       {refname: "urn:cspace:anthro.collectionspace.org:conceptauthorities:name(archculture):item:name(Blackfoot1576172504869)'Blackfoot'", csid: '1111-2222-3333-4444'}],
      ['conceptauthorities', 'concept', 'Birds',
       {refname: "urn:cspace:anthro.collectionspace.org:conceptauthorities:name(concept):item:name(Birds918181)'Birds'", csid: '1111-2222-3333-4444'}],
      ['conceptauthorities', 'ethculture', 'Batak',
       {refname: "urn:cspace:anthro.collectionspace.org:conceptauthorities:name(ethculture):item:name(Batak1576172496916)'Batak'", csid: '1111-2222-3333-4444'}],
      ['conceptauthorities', 'ethculture', 'Got',
       {refname: "urn:cspace:anthro.collectionspace.org:conceptauthorities:name(ethculture):item:name(Got1599824429903)'Got'", csid: '1111-2222-3333-4444'}],
      ['conceptauthorities', 'ethculture', 'Hero',
       {refname: "urn:cspace:anthro.collectionspace.org:conceptauthorities:name(ethculture):item:name(Hero1599824418804)'Hero'", csid: '1111-2222-3333-4444'}],
      ['conceptauthorities', 'material_ca', 'Feathers',
       {refname: "urn:cspace:anthro.collectionspace.org:conceptauthorities:name(material_ca):item:name(Feathers918181)'Feathers'", csid: '1111-2222-3333-4444'}],
      ['orgauthorities', 'organization', 'Hola',
       {refname: "urn:cspace:anthro.collectionspace.org:orgauthorities:name(organization):item:name(Hola1599824351945)'Hola'", csid: '1111-2222-3333-4444'}],
      ['orgauthorities', 'organization', 'Organization 1',
       {refname: "urn:cspace:anthro.collectionspace.org:orgauthorities:name(organization):item:name(Organization11587136583004)'Organization 1'", csid: '1111-2222-3333-4444'}],
      ['orgauthorities', 'organization', 'chores',
       {refname: "urn:cspace:anthro.collectionspace.org:orgauthorities:name(organization):item:name(chores1599824370125)'chores'", csid: '1111-2222-3333-4444'}],
      ['personauthorities', 'person', 'Ann Analyst',
       {refname: "urn:cspace:anthro.collectionspace.org:personauthorities:name(person):item:name(AnnAnalyst1594848799340)'Ann Analyst'", csid: '1111-2222-3333-4444'}],
      ['personauthorities', 'person', 'Gabriel Solares',
       {refname: "urn:cspace:anthro.collectionspace.org:personauthorities:name(person):item:name(GabrielSolares1594848906847)'Gabriel Solares'", csid: '1111-2222-3333-4444'}],
      ['personauthorities', 'person', 'Tegla',
       {refname: "urn:cspace:anthro.collectionspace.org:personauthorities:name(person):item:name(Tegla1599824325923)'Tegla'", csid: '1111-2222-3333-4444'}],
      ['personauthorities', 'person', 'Tom',
       {refname: "urn:cspace:anthro.collectionspace.org:personauthorities:name(person):item:name(Tom1599824331955)'Tom'", csid: '1111-2222-3333-4444'}],
      ['placeauthorities', 'place', 'Early',
       {refname: "urn:cspace:anthro.collectionspace.org:placeauthorities:name(place):item:name(Early1599824413345)'Early'", csid: '1111-2222-3333-4444'}],
      ['placeauthorities', 'place', 'Local',
       {refname: "urn:cspace:anthro.collectionspace.org:placeauthorities:name(place):item:name(Local1599824385298)'Local'", csid: '1111-2222-3333-4444'}],
      ['placeauthorities', 'place', 'York County, Pennsylvania',
       {refname: "urn:cspace:anthro.collectionspace.org:placeauthorities:name(place):item:name(YorkCountyPennsylvania)'York County, Pennsylvania'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'agerange', 'adolescent 26-75%',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(agerange):item:name(adolescent_26_75)'adolescent 26-75%'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'agerange', 'adult 0-25%',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(agerange):item:name(adult_0_25)'adult 0-25%'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'annotationtype', 'image made',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(annotationtype):item:name(image_made)'image made'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'annotationtype', 'type',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(annotationtype):item:name(type)'type'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'behrensmeyer', '0 - no cracking or flaking on bone surface',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(behrensmeyer):item:name(0)'0 - no cracking or flaking on bone surface'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'behrensmeyer', '1 - longitudinal and/or mosaic cracking present on surface',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(behrensmeyer):item:name(1)'1 - longitudinal and/or mosaic cracking present on surface'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'behrensmeyer', '2 - longitudinal cracks, exfoliation on surface',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(behrensmeyer):item:name(2)'2 - longitudinal cracks, exfoliation on surface'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'behrensmeyer', '3 - fibrous texture, extensive exfoliation',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(behrensmeyer):item:name(3)'3 - fibrous texture, extensive exfoliation'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'behrensmeyer', '5 - bone crumbling in situ, large splinters',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(behrensmeyer):item:name(5)'5 - bone crumbling in situ, large splinters'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'bodyside', 'midline',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(bodyside):item:name(midline)'midline'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'dateera', 'CE',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(dateera):item:name(ce)'CE'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'inventorystatus', 'accessioned',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(inventorystatus):item:name(accessioned)'accessioned'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'inventorystatus', 'unknown',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(inventorystatus):item:name(unknown)'unknown'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'languages', 'Chinese',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(languages):item:name(zho)'Chinese'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'languages', 'English',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(languages):item:name(eng)'English'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'languages', 'French',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(languages):item:name(fra)'French'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'languages', 'German',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(languages):item:name(deu)'German'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'languages', 'Spanish',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(languages):item:name(spa)'Spanish'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'limitationlevel', 'recommendation',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(limitationlevel):item:name(recommendation)'recommendation'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'limitationlevel', 'restriction',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(limitationlevel):item:name(restriction)'restriction'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'limitationtype', 'lending',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(limitationtype):item:name(lending)'lending'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'limitationtype', 'publication',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(limitationtype):item:name(publication)'publication'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'mortuarytreatment', 'burned/unburned bone mixture',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(mortuarytreatment):item:name(burnedunburnedbonemixture)'burned/unburned bone mixture'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'mortuarytreatment', 'enbalmed',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(mortuarytreatment):item:name(enbalmed)'enbalmed'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'mortuarytreatment', 'excarnated',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(mortuarytreatment):item:name(excarnated)'excarnated'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'mortuarytreatment', 'mummified',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(mortuarytreatment):item:name(mummified)'mummified'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'nagpracategory', 'not subject to NAGPRA',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(nagpracategory):item:name(nonNagpra)'not subject to NAGPRA'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'nagpracategory', 'subject to NAGPRA (unspec.)',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(nagpracategory):item:name(subjectToNAGPRA)'subject to NAGPRA (unspec.)'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'nagpraclaimtype', 'affiliated human skeletal remains (HSR)',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(nagpraclaimtype):item:name(affiliatedHsr)'affiliated human skeletal remains (HSR)'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'nagpraclaimtype', 'needs further research',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(nagpraclaimtype):item:name(needsFurtherResearch)'needs further research'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'nagpraclaimtype', 'not subject to NAGPRA',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(nagpraclaimtype):item:name(nonNagpra)'not subject to NAGPRA'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'nagpraclaimtype', 'object of cultural patrimony',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(nagpraclaimtype):item:name(objectOfCulturalPatrimony)'object of cultural patrimony'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'nagpraclaimtype', 'unassociated funerary object (UFO)',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(nagpraclaimtype):item:name(ufo)'unassociated funerary object (UFO)'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'prodpeoplerole', 'designed after',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(prodpeoplerole):item:name(designedAfter)'designed after'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'prodpeoplerole', 'traditional makers',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(prodpeoplerole):item:name(traditionalMakers)'traditional makers'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'publishto', 'DPLA',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(publishto):item:name(dpla)'DPLA'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'publishto', 'Omeka',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(publishto):item:name(omeka)'Omeka'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'cranialdeformationcategory', 'other (describe)',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(cranialdeformationcategory):item:name(other)'other (describe)'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'cranialdeformationcategory', 'tabular',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(cranialdeformationcategory):item:name(tabular)'tabular'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'cranialdeformationcategory', 'circumferential',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(cranialdeformationcategory):item:name(circumferential)'circumferential'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'trepanationcertainty', 'possible trepanation',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(trepanationcertainty):item:name(possible)'possible trepanation'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'trepanationcertainty', 'clear evidence of trepanation',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(trepanationcertainty):item:name(clear)'clear evidence of trepanation'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'trepanationtechnique', 'grooving',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(trepanationtechnique):item:name(grooving)'grooving'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'trepanationtechnique', 'grooving',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(trepanationtechnique):item:name(grooving)'grooving'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'trepanationhealing', 'possible healing',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(trepanationhealing):item:name(possible)'possible healing'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'trepanationhealing', 'no healing',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(trepanationhealing):item:name(none)'no healing'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'trepanationhealing', 'definite evidence for healing',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(trepanationhealing):item:name(definite)'definite evidence for healing'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'mortuarytreatment', 'excarnated',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(mortuarytreatment):item:name(excarnated)'excarnated'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'behrensmeyer', '3 - fibrous texture, extensive exfoliation',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(behrensmeyer):item:name(3)'3 - fibrous texture, extensive exfoliation'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'dateera', 'CE',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(dateera):item:name(ce)'CE'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'dateera', 'CE',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(dateera):item:name(ce)'CE'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'dateera', 'CE',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(dateera):item:name(ce)'CE'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'dateera', 'CE',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(dateera):item:name(ce)'CE'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'osteocompleteness', 'mandible only',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(osteocompleteness):item:name(mandible)'mandible only'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'behrensmeyer',
       '4 - coarsely fibrous texture, splinters of bone loose on the surface, open cracks', {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(behrensmeyer):item:name(4)'4 - coarsely fibrous texture, splinters of bone loose on the surface, open cracks'", csid: '1111-2222-3333-4444'}],
      ['vocabularies', 'dentitionscore', 'not applicable',
       {refname: "urn:cspace:anthro.collectionspace.org:vocabularies:name(dentitionscore):item:name(notapplicable)'not applicable'", csid: '1111-2222-3333-4444'}],
      ['personauthorities', 'person', 'sniper',
       {refname: "urn:cspace:anthro.collectionspace.org:personauthorities:name(person):item:name(sniper1599821165616)'sniper'", csid: '1111-2222-3333-4444'}],
      ['personauthorities', 'person', 'fullclip',
       {refname: "urn:cspace:anthro.collectionspace.org:personauthorities:name(person):item:name(fullclip1599821193344)'fullclip'", csid: '1111-2222-3333-4444'}],
      ['personauthorities', 'person', 'fullclip',
       {refname: "urn:cspace:anthro.collectionspace.org:personauthorities:name(person):item:name(fullclip1599821140041)'fullclip'", csid: '1111-2222-3333-4444'}],
      ['personauthorities', 'person', 'praya',
       {refname: "urn:cspace:anthro.collectionspace.org:personauthorities:name(person):item:name(praya1599821095120)'praya'", csid: '1111-2222-3333-4444'}],
      ['personauthorities', 'person', 'jijoe',
       {refname: "urn:cspace:anthro.collectionspace.org:personauthorities:name(person):item:name(jijoe1599821246989)'jijoe'", csid: '1111-2222-3333-4444'}]
    ]
    populate(cache, terms)
  end

  def anthro_co_1
    get_datahash(path: 'spec/fixtures/files/datahashes/anthro/collectionobject1.json')
  end
end
