# frozen_string_literal: true

module Helpers
  def cacheable_refnames(domain)
    # rubocop:disable Layout/LineLength
    [
      ["citationauthorities", "citation", "Arthur",
        "urn:cspace:DOMAIN:citationauthorities:name(citation):item:name(Arthur62605812848)'Arthur'"],
      ["citationauthorities", "citation", "FNA Volume 19",
        "urn:cspace:DOMAIN:citationauthorities:name(citation):item:name(FNAVolume191599238760383)'FNA Volume 19'"],
      ["citationauthorities", "citation", "Harding",
        "urn:cspace:DOMAIN:citationauthorities:name(citation):item:name(Harding2510592089)'Harding'"],
      ["citationauthorities", "citation", "Sp. Pl. 2: 899. 1753",
        "urn:cspace:DOMAIN:citationauthorities:name(citation):item:name(SpPl289917531599238184211)'Sp. Pl. 2: 899. 1753'"],
      ["citationauthorities", "citation", "Wanting",
        "urn:cspace:DOMAIN:citationauthorities:name(citation):item:name(Wanting1599560009399)'Wanting'"],
      ["citationauthorities", "citation", "makasi",
        "urn:cspace:DOMAIN:citationauthorities:name(citation):item:name(makasi1599645537547)'makasi'"],
      ["citationauthorities", "worldcat", "Bull. Torrey Bot. Club",
        "urn:cspace:DOMAIN:citationauthorities:name(worldcat):item:name(BullTorreyBotClub331599245358364)'Bull. Torrey Bot. Club'"],
      ["citationauthorities", "worldcat", "Chelse",
        "urn:cspace:DOMAIN:citationauthorities:name(worldcat):item:name(Chelse1599645525740)'Chelse'"],
      ["citationauthorities", "worldcat", "Patiently",
        "urn:cspace:DOMAIN:citationauthorities:name(worldcat):item:name(Patiently1599559993332)'Patiently'"],
      ["conceptauthorities", "archculture", "Blackfoot",
        "urn:cspace:DOMAIN:conceptauthorities:name(archculture):item:name(Blackfoot1576172504869)'Blackfoot'"],
      ["conceptauthorities", "concept", "Birds",
        "urn:cspace:DOMAIN:conceptauthorities:name(concept):item:name(Birds918181)'Birds'"],
      ["conceptauthorities", "concept", "Official",
        "urn:cspace:DOMAIN:conceptauthorities:name(concept):item:name(Official1599737276242)'Official'"],
      ["conceptauthorities", "concept", "Sample Concept 1",
        "urn:cspace:DOMAIN:conceptauthorities:name(concept):item:name(SampleConcept11581354228875)'Sample Concept 1'"],
      ["conceptauthorities", "concept", "Test",
        "urn:cspace:DOMAIN:conceptauthorities:name(concept):item:name(Test1599650854716)'Test'"],
      ["conceptauthorities", "concept", "Uno",
        "urn:cspace:DOMAIN:conceptauthorities:name(concept):item:name(Uno1599645111177)'Uno'"],
      ["conceptauthorities", "ethculture", "Batak",
        "urn:cspace:DOMAIN:conceptauthorities:name(ethculture):item:name(Batak1576172496916)'Batak'"],
      ["conceptauthorities", "ethculture", "Got",
        "urn:cspace:DOMAIN:conceptauthorities:name(ethculture):item:name(Got1599824429903)'Got'"],
      ["conceptauthorities", "ethculture", "Hero",
        "urn:cspace:DOMAIN:conceptauthorities:name(ethculture):item:name(Hero1599824418804)'Hero'"],
      ["conceptauthorities", "material_ca", "Feathers",
        "urn:cspace:DOMAIN:conceptauthorities:name(material_ca):item:name(Feathers918181)'Feathers'"],
      ["conceptauthorities", "occasion", "Computer",
        "urn:cspace:DOMAIN:conceptauthorities:name(occasion):item:name(Computer1599734104251)'Computer'"],
      ["locationauthorities", "indeterminate", "~Indeterminate Location~",
        "urn:cspace:indeterminate:locationauthorities:name(indeterminate):item:name(indeterminate)'~Indeterminate Location~'"],
      ["locationauthorities", "location", "Abardares",
        "urn:cspace:DOMAIN:locationauthorities:name(location):item:name(Abardares1599557570049)'Abardares'"],
      ["locationauthorities", "location", "Corner",
        "urn:cspace:DOMAIN:locationauthorities:name(location):item:name(Corner1599737289184)'Corner'"],
      ["locationauthorities", "location", "Kalif",
        "urn:cspace:DOMAIN:locationauthorities:name(location):item:name(Kalif1599734233745)'Kalif'"],
      ["locationauthorities", "location", "Khago",
        "urn:cspace:DOMAIN:locationauthorities:name(location):item:name(Khago1599559772718)'Khago'"],
      ["locationauthorities", "location", "Stay",
        "urn:cspace:DOMAIN:locationauthorities:name(offsite_sla):item:name(Stay1599559824865)'Stay'"],
      ["locationauthorities", "offsite_sla", "Lavington",
        "urn:cspace:DOMAIN:locationauthorities:name(offsite_sla):item:name(Lavington1599144699983)'Lavington'"],
      ["locationauthorities", "offsite_sla", "Ngong",
        "urn:cspace:DOMAIN:locationauthorities:name(offsite_sla):item:name(Ngong1599557586466)'Ngong'"],
      ["locationauthorities", "offsite_sla", "Stay",
        "urn:cspace:DOMAIN:locationauthorities:name(offsite_sla):item:name(Stay)'Stay'"],
      ["orgauthorities", "organization", "2021",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(20211599147173971)'2021'"],
      ["orgauthorities", "organization", "Astroworld",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Astroworld1599650794829)'Astroworld'"],
      ["orgauthorities", "organization", "Bonsai Museum",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(BonsaiMuseum1598919439027)'Bonsai Museum'"],
      ["orgauthorities", "organization", "Bonsai Store",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(BonsaiStore1598920297843)'Bonsai Store'"],
      ["orgauthorities", "organization", "Broker",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Broker1599221487572)'Broker'"],
      ["orgauthorities", "organization", "But Ohh",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(ButOhh1599665031368)'But Ohh'"],
      ["orgauthorities", "organization", "Cuckoo",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Cuckoo1599463786824)'Cuckoo'"],
      ["orgauthorities", "organization", "FVA",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(FVA1599246022216)'FVA'"],
      ["orgauthorities", "organization", "Hola",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Hola1599824351945)'Hola'"],
      ["orgauthorities", "organization", "Ibiza",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Ibiza1599650806827)'Ibiza'"],
      ["orgauthorities", "organization", "Joseph Hills",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(JosephHills1599463935463)'Joseph Hills'"],
      ["orgauthorities", "organization", "Kremling",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Kremling1599464161204)'Kremling'"],
      ["orgauthorities", "organization", "MMG",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(MMG1599569514486)'MMG'"],
      ["orgauthorities", "organization", "Martin",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Martin1599559712783)'Martin'"],
      ["orgauthorities", "organization", "Ninja",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Ninja1599147339325)'Ninja'"],
      ["orgauthorities", "organization", "Organization 1",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Organization11587136583004)'Organization 1'"],
      ["orgauthorities", "organization", "Oval",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Oval1599650891221)'Oval'"],
      ["orgauthorities", "organization", "Podoa",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Podoa1599645346399)'Podoa'"],
      ["orgauthorities", "organization", "Rock Nation",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(RockNation1599569481908)'Rock Nation'"],
      ["orgauthorities", "organization", "Sidarec",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Sidarec1599210955079)'Sidarec'"],
      ["orgauthorities", "organization", "TIm Herod",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(TImHerod1599144655199)'TIm Herod'"],
      ["orgauthorities", "organization", "Tasia",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Tasia1599734050597)'Tasia'"],
      ["orgauthorities", "organization", "Tesla",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Tesla1599144565539)'Tesla'"],
      ["orgauthorities", "organization", "Walai",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(Walai1599645181370)'Walai'"],
      ["orgauthorities", "organization", "breakup",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(breakup1599559909048)'breakup'"],
      ["orgauthorities", "organization", "chores",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(chores1599824370125)'chores'"],
      ["orgauthorities", "organization", "fggf",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(fggf1599552009173)'fggf'"],
      ["orgauthorities", "organization", "pandemic",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(pandemic1599645036126)'pandemic'"],
      ["orgauthorities", "organization", "pop",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(pop1599664789385)'pop'"],
      ["orgauthorities", "organization", "pupu",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(pupu1599645415676)'pupu'"],
      ["orgauthorities", "organization", "tent",
        "urn:cspace:DOMAIN:orgauthorities:name(organization):item:name(tent1599664807586)'tent'"],
      ["orgauthorities", "ulan_oa", "Again",
        "urn:cspace:DOMAIN:orgauthorities:name(ulan_oa):item:name(Again1599559881266)'Again'"],
      ["orgauthorities", "ulan_oa", "Signal",
        "urn:cspace:DOMAIN:orgauthorities:name(ulan_oa):item:name(Signal1599559737158)'Signal'"],
      ["orgauthorities", "ulan_oa", "Very fats",
        "urn:cspace:DOMAIN:orgauthorities:name(ulan_oa):item:name(Veryfats1599645188567)'Very fats'"],
      ["personauthorities", "person", "2020",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(20201599147149106)'2020'"],
      ["personauthorities", "person", "254Glock",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(254Glock1599569494651)'254Glock'"],
      ["personauthorities", "person", "Abel",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Abel1599464025893)'Abel'"],
      ["personauthorities", "person", "Alexa",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Alexa1599557607978)'Alexa'"],
      ["personauthorities", "person", "Andrew Watts",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(AndrewWatts1599144553996)'Andrew Watts'"],
      ["personauthorities", "person", "Ann Analyst",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(AnnAnalyst1594848799340)'Ann Analyst'"],
      ["personauthorities", "person", "Ann Authorizer",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(AnnAuthorizer1598919551068)'Ann Authorizer'"],
      ["personauthorities", "person", "Broooks",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Broooks1599221558583)'Broooks'"],
      ["personauthorities", "person", "Busy",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Busy1599559723432)'Busy'"],
      ["personauthorities", "person", "Cardi",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Cardi1599569468209)'Cardi'"],
      ["personauthorities", "person", "Clemo",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Clemo1599221473000)'Clemo'"],
      ["personauthorities", "person", "Clon",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Clon1599569543362)'Clon'"],
      ["personauthorities", "person", "Comodore",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Comodore1599463826401)'Comodore'"],
      ["personauthorities", "person", "Comrade",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Comrade1599664745661)'Comrade'"],
      ["personauthorities", "person", "Cooper Phil",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(CooperPhil1599144599479)'Cooper Phil'"],
      ["personauthorities", "person", "Debbie Depositor",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(DebbieDepositor1598919493867)'Debbie Depositor'"],
      ["personauthorities", "person", "Disturb",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Disturb1599665062738)'Disturb'"],
      ["personauthorities", "person", "Dudu",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Dudu1599645410044)'Dudu'"],
      ["personauthorities", "person", "Elizabeth",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Elizabeth123)'Elizabeth'"],
      ["personauthorities", "person", "Erick",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Erick1599734121151)'Erick'"],
      ["personauthorities", "person", "First Layer",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(FirstLayer1599463905818)'First Layer'"],
      ["personauthorities", "person", "Gabriel Solares",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(GabrielSolares1594848906847)'Gabriel Solares'"],
      ["personauthorities", "person", "Glock",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Glock1599580905730)'Glock'"],
      ["personauthorities", "person", "Gomongo",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Gomongo1599463746195)'Gomongo'"],
      ["personauthorities", "person", "Grace",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Grace1599569599918)'Grace'"],
      ["personauthorities", "person", "Henry",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Henry1599210937770)'Henry'"],
      ["personauthorities", "person", "Home Alone",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(HomeAlone1599144524188)'Home Alone'"],
      ["personauthorities", "person", "James",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(James1599210943727)'James'"],
      ["personauthorities", "person", "Jamo",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Jamo1599221465693)'Jamo'"],
      ["personauthorities", "person", "Joel",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Joel1599557736045)'Joel'"],
      ["personauthorities", "person", "John Allen",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(JohnAllen1599144390263)'John Allen'"],
      ["personauthorities", "person", "John Doe",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(JohnDoe1416422840)'John Doe'"],
      ["personauthorities", "person", "John Kay",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(JohnKay1599210868122)'John Kay'"],
      ["personauthorities", "person", "Kali",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Kali1599221504661)'Kali'"],
      ["personauthorities", "person", "Karanja",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Karanja1599211015378)'Karanja'"],
      ["personauthorities", "person", "Kev",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Kev1599058769862)'Kev'"],
      ["personauthorities", "person", "Kimani",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Kimani1599210926973)'Kimani'"],
      ["personauthorities", "person", "Kimonda",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Kimonda1599211004900)'Kimonda'"],
      ["personauthorities", "person", "King Kosa",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(KingKosa1599569726990)'King Kosa'"],
      ["personauthorities", "person", "Kinuthia",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Kinuthia1599734017515)'Kinuthia'"],
      ["personauthorities", "person", "Lebron",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Lebron1599557725925)'Lebron'"],
      ["personauthorities", "person", "Lima",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Lima1599645323459)'Lima'"],
      ["personauthorities", "person", "Linnaeus, Carl",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(LinnaeusCarl1599238374086)'Linnaeus, Carl'"],
      ["personauthorities", "person", "Loan",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Loan1599210896616)'Loan'"],
      ["personauthorities", "person", "Mark Smith",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(MarkSmith)'Mark Smith'"],
      ["personauthorities", "person", "Meghan",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Meghan1599569567326)'Meghan'"],
      ["personauthorities", "person", "Nyauma",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Nyauma1599210983879)'Nyauma'"],
      ["personauthorities", "person", "Priscilla Plantsale",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(PriscillaPlantsale1598920259864)'Priscilla Plantsale'"],
      ["personauthorities", "person", "Scribe",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Scribe1599645240974)'Scribe'"],
      ["personauthorities", "person", "Shen Yeng",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(ShenYeng1599569685887)'Shen Yeng'"],
      ["personauthorities", "person", "Soi",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Soi1599734190999)'Soi'"],
      ["personauthorities", "person", "Switch",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Switch1599645085995)'Switch'"],
      ["personauthorities", "person", "Tegla",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Tegla1599824325923)'Tegla'"],
      ["personauthorities", "person", "Tim Joes",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(TimJoes1599144424859)'Tim Joes'"],
      ["personauthorities", "person", "Tom",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Tom1599824331955)'Tom'"],
      ["personauthorities", "person", "Trepoz",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Trepoz1599221497512)'Trepoz'"],
      ["personauthorities", "person", "Trevor",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Trevor1599144536281)'Trevor'"],
      ["personauthorities", "person", "Troy",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(Troy1599144360617)'Troy'"],
      ["personauthorities", "person", "afa",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(afa1599645004939)'afa'"],
      ["personauthorities", "person", "cxcx",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(cxcx1599551790384)'cxcx'"],
      ["personauthorities", "person", "dfdd",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(dfdd1599551799173)'dfdd'"],
      ["personauthorities", "person", "dssd",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(dssd1599552004115)'dssd'"],
      ["personauthorities", "person", "fgfgf",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(fgfgf1599551987166)'fgfgf'"],
      ["personauthorities", "person", "fullclip",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(fullclip1599821193344)'fullclip'"],
      ["personauthorities", "person", "giri",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(giri1599645613143)'giri'"],
      ["personauthorities", "person", "high grade",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(highgrade1599645597889)'high grade'"],
      ["personauthorities", "person", "jijoe",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(jijoe1599821246989)'jijoe'"],
      ["personauthorities", "person", "malik",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(malik1599664876144)'malik'"],
      ["personauthorities", "person", "marcus",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(marcus1599650918612)'marcus'"],
      ["personauthorities", "person", "marley",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(marley1599650874712)'marley'"],
      ["personauthorities", "person", "praya",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(praya1599821095120)'praya'"],
      ["personauthorities", "person", "rights",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(rights1599650868011)'rights'"],
      ["personauthorities", "person", "rudelyt",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(rudelyt1599664917218)'rudelyt'"],
      ["personauthorities", "person", "sasa",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(sasa1599551852678)'sasa'"],
      ["personauthorities", "person", "sniper",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(sniper1599821165616)'sniper'"],
      ["personauthorities", "person", "tint",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(tint1599664800144)'tint'"],
      ["personauthorities", "person", "tonight",
        "urn:cspace:DOMAIN:personauthorities:name(person):item:name(tonight1599664781376)'tonight'"],
      ["personauthorities", "ulan_pa", "Chrus",
        "urn:cspace:DOMAIN:personauthorities:name(ulan_pa):item:name(Chrus1599559702930)'Chrus'"],
      ["personauthorities", "ulan_pa", "We go",
        "urn:cspace:DOMAIN:personauthorities:name(ulan_pa):item:name(Wego1599559866517)'We go'"],
      ["personauthorities", "ulan_pa", "panda nayo",
        "urn:cspace:DOMAIN:personauthorities:name(ulan_pa):item:name(pandanayo1599645094507)'panda nayo'"],
      ["placeauthorities", "place", "Chillspot",
        "urn:cspace:DOMAIN:placeauthorities:name(place):item:name(Chillspot1599145441945)'Chillspot'"],
      ["placeauthorities", "place", "Early",
        "urn:cspace:DOMAIN:placeauthorities:name(place):item:name(Early1599824413345)'Early'"],
      ["placeauthorities", "place", "Local",
        "urn:cspace:DOMAIN:placeauthorities:name(place):item:name(Local1599824385298)'Local'"],
      ["placeauthorities", "place", "York County, Pennsylvania",
        "urn:cspace:DOMAIN:placeauthorities:name(place):item:name(YorkCountyPennsylvania)'York County, Pennsylvania'"],
      ["placeauthorities", "tgn_place", "mzingga",
        "urn:cspace:DOMAIN:placeauthorities:name(tgn_place):item:name(mzingga1599645587502)'mzingga'"],
      ["taxonomyauthority", "taxon", "Domestic",
        "urn:cspace:DOMAIN:taxonomyauthority:name(taxon):item:name(Domestic1599750187683)'Domestic'"],
      ["taxonomyauthority", "taxon", "Tropez",
        "urn:cspace:DOMAIN:taxonomyauthority:name(taxon):item:name(Tropez1599750195530)'Tropez'"],
      ["vocabularies", "agequalifier", "older than",
        "urn:cspace:DOMAIN:vocabularies:name(agequalifier):item:name(olderthan)'older than'"],
      ["vocabularies", "agerange", "adolescent 26-75%",
        "urn:cspace:DOMAIN:vocabularies:name(agerange):item:name(adolescent_26_75)'adolescent 26-75%'"],
      ["vocabularies", "agerange", "adult 0-25%",
        "urn:cspace:DOMAIN:vocabularies:name(agerange):item:name(adult_0_25)'adult 0-25%'"],
      ["vocabularies", "annotationtype", "image made",
        "urn:cspace:DOMAIN:vocabularies:name(annotationtype):item:name(image_made)'image made from cache'"],
      ["vocabularies", "annotationtype", "type",
        "urn:cspace:DOMAIN:vocabularies:name(annotationtype):item:name(type)'type'"],
      ["vocabularies", "behrensmeyer",
        "0 - no cracking or flaking on bone surface", "urn:cspace:DOMAIN:vocabularies:name(behrensmeyer):item:name(0)'0 - no cracking or flaking on bone surface'"],
      ["vocabularies", "behrensmeyer",
        "1 - longitudinal and/or mosaic cracking present on surface", "urn:cspace:DOMAIN:vocabularies:name(behrensmeyer):item:name(1)'1 - longitudinal and/or mosaic cracking present on surface'"],
      ["vocabularies", "behrensmeyer",
        "2 - longitudinal cracks, exfoliation on surface", "urn:cspace:DOMAIN:vocabularies:name(behrensmeyer):item:name(2)'2 - longitudinal cracks, exfoliation on surface'"],
      ["vocabularies", "behrensmeyer",
        "3 - fibrous texture, extensive exfoliation", "urn:cspace:DOMAIN:vocabularies:name(behrensmeyer):item:name(3)'3 - fibrous texture, extensive exfoliation'"],
      ["vocabularies", "behrensmeyer",
        "4 - coarsely fibrous texture, splinters of bone loose on the surface, open cracks", "urn:cspace:DOMAIN:vocabularies:name(behrensmeyer):item:name(4)'4 - coarsely fibrous texture, splinters of bone loose on the surface, open cracks'"],
      ["vocabularies", "behrensmeyer",
        "5 - bone crumbling in situ, large splinters", "urn:cspace:DOMAIN:vocabularies:name(behrensmeyer):item:name(5)'5 - bone crumbling in situ, large splinters'"],
      ["vocabularies", "bodyside", "midline",
        "urn:cspace:DOMAIN:vocabularies:name(bodyside):item:name(midline)'midline'"],
      ["vocabularies", "collectionmethod", "donation",
        "urn:cspace:DOMAIN:vocabularies:name(collectionmethod):item:name(donation)'donation'"],
      ["vocabularies", "collectionmethod", "excavation",
        "urn:cspace:DOMAIN:vocabularies:name(collectionmethod):item:name(excavation)'excavation'"],
      ["vocabularies", "conditioncheckmethod", "Observed",
        "urn:cspace:DOMAIN:vocabularies:name(conditioncheckmethod):item:name(observed)'Observed'"],
      ["vocabularies", "conditioncheckreason", "Damaged in transit",
        "urn:cspace:DOMAIN:vocabularies:name(conditioncheckreason):item:name(damagedintransit)'Damaged in transit'"],
      ["vocabularies", "conditionfitness", "Reasonable",
        "urn:cspace:DOMAIN:vocabularies:name(conditionfitness):item:name(reasonable)'Reasonable'"],
      ["vocabularies", "conservationstatus", "Analysis complete",
        "urn:cspace:DOMAIN:vocabularies:name(conservationstatus):item:name(analysiscomplete)'Analysis complete'"],
      ["vocabularies", "conservationstatus", "Treatment approved",
        "urn:cspace:DOMAIN:vocabularies:name(conservationstatus):item:name(treatmentapproved)'Treatment approved'"],
      ["vocabularies", "conservationstatus", "Treatment in progress",
        "urn:cspace:DOMAIN:vocabularies:name(conservationstatus):item:name(treatmentinprogress)'Treatment in progress'"],
      ["vocabularies", "cranialdeformationcategory", "circumferential",
        "urn:cspace:DOMAIN:vocabularies:name(cranialdeformationcategory):item:name(circumferential)'circumferential'"],
      ["vocabularies", "cranialdeformationcategory", "other (describe)",
        "urn:cspace:DOMAIN:vocabularies:name(cranialdeformationcategory):item:name(other)'other (describe)'"],
      ["vocabularies", "cranialdeformationcategory", "tabular",
        "urn:cspace:DOMAIN:vocabularies:name(cranialdeformationcategory):item:name(tabular)'tabular'"],
      ["vocabularies", "currency", "Canadian Dollar",
        "urn:cspace:DOMAIN:vocabularies:name(currency):item:name(CAD)'Canadian Dollar'"],
      ["vocabularies", "currency", "Danish Krone",
        "urn:cspace:DOMAIN:vocabularies:name(currency):item:name(DKK)'Danish Krone'"],
      ["vocabularies", "currency", "Euro",
        "urn:cspace:DOMAIN:vocabularies:name(currency):item:name(EUR)'Euro'"],
      ["vocabularies", "currency", "Pound Sterling",
        "urn:cspace:DOMAIN:vocabularies:name(currency):item:name(GBP)'Pound Sterling'"],
      ["vocabularies", "currency", "Swedish Krona",
        "urn:cspace:DOMAIN:vocabularies:name(currency):item:name(SEK)'Swedish Krona'"],
      ["vocabularies", "currency", "Swiss Franc",
        "urn:cspace:DOMAIN:vocabularies:name(currency):item:name(CHF)'Swiss Franc'"],
      ["vocabularies", "cuttingtype", "hardwood",
        "urn:cspace:DOMAIN:vocabularies:name(cuttingtype):item:name(hardwood)'hardwood'"],
      ["vocabularies", "datecertainty", "Circa",
        "urn:cspace:DOMAIN:vocabularies:name(datecertainty):item:name(circa)'Circa'"],
      ["vocabularies", "dateera", "BCE",
        "urn:cspace:DOMAIN:vocabularies:name(dateera):item:name(bce)'BCE'"],
      ["vocabularies", "dateera", "CE",
        "urn:cspace:DOMAIN:vocabularies:name(dateera):item:name(ce)'CE'"],
      ["vocabularies", "datequalifier", "Day(s)",
        "urn:cspace:DOMAIN:vocabularies:name(datequalifier):item:name(days)'Day(s)'"],
      ["vocabularies", "datequalifier", "Year(s)",
        "urn:cspace:DOMAIN:vocabularies:name(datequalifier):item:name(years)'Year(s)'"],
      ["vocabularies", "deaccessionapprovalgroup", "board of trustees",
        "urn:cspace:DOMAIN:vocabularies:name(deaccessionapprovalgroup):item:name(board_of_trustees)'board of trustees'"],
      ["vocabularies", "deaccessionapprovalgroup", "collection committee",
        "urn:cspace:DOMAIN:vocabularies:name(deaccessionapprovalgroup):item:name(collection_committee)'collection committee'"],
      ["vocabularies", "deaccessionapprovalgroup", "executive committee",
        "urn:cspace:DOMAIN:vocabularies:name(deaccessionapprovalgroup):item:name(executive_committee)'executive committee'"],
      ["vocabularies", "deaccessionapprovalstatus", "approved",
        "urn:cspace:DOMAIN:vocabularies:name(deaccessionapprovalstatus):item:name(approved)'approved'"],
      ["vocabularies", "deaccessionapprovalstatus", "not approved",
        "urn:cspace:DOMAIN:vocabularies:name(deaccessionapprovalstatus):item:name(not_approved)'not approved'"],
      ["vocabularies", "deaccessionapprovalstatus", "not required",
        "urn:cspace:DOMAIN:vocabularies:name(deaccessionapprovalstatus):item:name(not_required)'not required'"],
      ["vocabularies", "dentitionscore", "not applicable",
        "urn:cspace:DOMAIN:vocabularies:name(dentitionscore):item:name(notapplicable)'not applicable'"],
      ["vocabularies", "disposalmethod", "destruction",
        "urn:cspace:DOMAIN:vocabularies:name(disposalmethod):item:name(destruction)'destruction'"],
      ["vocabularies", "disposalmethod", "public auction",
        "urn:cspace:DOMAIN:vocabularies:name(disposalmethod):item:name(public_auction)'public auction'"],
      ["vocabularies", "durationunit", "Days",
        "urn:cspace:DOMAIN:vocabularies:name(durationunit):item:name(days)'Days'"],
      ["vocabularies", "durationunit", "Hours",
        "urn:cspace:DOMAIN:vocabularies:name(durationunit):item:name(hours)'Hours'"],
      ["vocabularies", "entrymethod", "Found on doorstep",
        "urn:cspace:DOMAIN:vocabularies:name(entrymethod):item:name(foundondoorstep)'Found on doorstep'"],
      ["vocabularies", "entrymethod", "Post",
        "urn:cspace:DOMAIN:vocabularies:name(entrymethod):item:name(post)'Post'"],
      ["vocabularies", "examinationphase", "before treatment",
        "urn:cspace:DOMAIN:vocabularies:name(examinationphase):item:name(beforetreatment)'before treatment'"],
      ["vocabularies", "examinationphase", "during treatment",
        "urn:cspace:DOMAIN:vocabularies:name(examinationphase):item:name(duringtreatment)'during treatment'"],
      ["vocabularies", "exhibitionpersonrole", "Educator",
        "urn:cspace:DOMAIN:vocabularies:name(exhibitionpersonrole):item:name(educator)'Educator'"],
      ["vocabularies", "exhibitionpersonrole", "Public programs coordinator",
        "urn:cspace:DOMAIN:vocabularies:name(exhibitionpersonrole):item:name(publicprogramscoordinator)'Public programs coordinator'"],
      ["vocabularies", "exhibitionreferencetype", "News article",
        "urn:cspace:DOMAIN:vocabularies:name(exhibitionreferencetype):item:name(newsarticle)'News article'"],
      ["vocabularies", "exhibitionreferencetype", "Press release",
        "urn:cspace:DOMAIN:vocabularies:name(exhibitionreferencetype):item:name(pressrelease)'Press release'"],
      ["vocabularies", "exhibitionstatus", "Preliminary object list created",
        "urn:cspace:DOMAIN:vocabularies:name(exhibitionstatus):item:name(preliminaryobjectlistcreated)'Preliminary object list created'"],
      ["vocabularies", "exhibitiontype", "Temporary",
        "urn:cspace:DOMAIN:vocabularies:name(exhibitiontype):item:name(temporary)'Temporary'"],
      ["vocabularies", "inventorystatus", "accession status unclear",
        "urn:cspace:DOMAIN:vocabularies:name(inventorystatus):item:name(accessionstatusunclear)'accession status unclear'"],
      ["vocabularies", "inventorystatus", "accessioned",
        "urn:cspace:DOMAIN:vocabularies:name(inventorystatus):item:name(accessioned)'accessioned'"],
      ["vocabularies", "inventorystatus", "destroyed",
        "urn:cspace:DOMAIN:vocabularies:name(inventorystatus):item:name(destroyed)'destroyed'"],
      ["vocabularies", "inventorystatus", "unknown",
        "urn:cspace:DOMAIN:vocabularies:name(inventorystatus):item:name(unknown)'unknown'"],
      ["vocabularies", "languages", "Ancient Greek",
        "urn:cspace:DOMAIN:vocabularies:name(languages):item:name(grc)'Ancient Greek'"],
      ["vocabularies", "languages", "Armenian",
        "urn:cspace:DOMAIN:vocabularies:name(languages):item:name(hye)'Armenian'"],
      ["vocabularies", "languages", "Chinese",
        "urn:cspace:DOMAIN:vocabularies:name(languages):item:name(zho)'Chinese'"],
      ["vocabularies", "languages", "English",
        "urn:cspace:DOMAIN:vocabularies:name(languages):item:name(eng)'English'"],
      ["vocabularies", "languages", "French",
        "urn:cspace:DOMAIN:vocabularies:name(languages):item:name(fra)'French'"],
      ["vocabularies", "languages", "German",
        "urn:cspace:DOMAIN:vocabularies:name(languages):item:name(deu)'German'"],
      ["vocabularies", "languages", "Latin",
        "urn:cspace:DOMAIN:vocabularies:name(languages):item:name(lat)'Latin'"],
      ["vocabularies", "languages", "Malaysian",
        "urn:cspace:DOMAIN:vocabularies:name(languages):item:name(mal)'Malaysian'"],
      ["vocabularies", "languages", "Spanish",
        "urn:cspace:DOMAIN:vocabularies:name(languages):item:name(spa)'Spanish'"],
      ["vocabularies", "languages", "Swahili",
        "urn:cspace:DOMAIN:vocabularies:name(languages):item:name(swa)'Swahili'"],
      ["vocabularies", "limitationlevel", "recommendation",
        "urn:cspace:DOMAIN:vocabularies:name(limitationlevel):item:name(recommendation)'recommendation'"],
      ["vocabularies", "limitationlevel", "restriction",
        "urn:cspace:DOMAIN:vocabularies:name(limitationlevel):item:name(restriction)'restriction'"],
      ["vocabularies", "limitationtype", "lending",
        "urn:cspace:DOMAIN:vocabularies:name(limitationtype):item:name(lending)'lending'"],
      ["vocabularies", "limitationtype", "publication",
        "urn:cspace:DOMAIN:vocabularies:name(limitationtype):item:name(publication)'publication'"],
      ["vocabularies", "loanoutstatus", "Authorized",
        "urn:cspace:DOMAIN:vocabularies:name(loanoutstatus):item:name(authorized)'Authorized'"],
      ["vocabularies", "loanoutstatus", "Photography requested",
        "urn:cspace:DOMAIN:vocabularies:name(loanoutstatus):item:name(photographyrequested)'Photography requested'"],
      ["vocabularies", "loanoutstatus", "Refused",
        "urn:cspace:DOMAIN:vocabularies:name(loanoutstatus):item:name(refused)'Refused'"],
      ["vocabularies", "loanoutstatus", "Returned",
        "urn:cspace:DOMAIN:vocabularies:name(loanoutstatus):item:name(returned)'Returned'"],
      ["vocabularies", "mortuarytreatment", "burned/unburned bone mixture",
        "urn:cspace:DOMAIN:vocabularies:name(mortuarytreatment):item:name(burnedunburnedbonemixture)'burned/unburned bone mixture'"],
      ["vocabularies", "mortuarytreatment", "enbalmed",
        "urn:cspace:DOMAIN:vocabularies:name(mortuarytreatment):item:name(enbalmed)'enbalmed'"],
      ["vocabularies", "mortuarytreatment", "excarnated",
        "urn:cspace:DOMAIN:vocabularies:name(mortuarytreatment):item:name(excarnated)'excarnated'"],
      ["vocabularies", "mortuarytreatment", "mummified",
        "urn:cspace:DOMAIN:vocabularies:name(mortuarytreatment):item:name(mummified)'mummified'"],
      ["vocabularies", "nagpracategory", "not subject to NAGPRA",
        "urn:cspace:DOMAIN:vocabularies:name(nagpracategory):item:name(nonNagpra)'not subject to NAGPRA'"],
      ["vocabularies", "nagpracategory", "subject to NAGPRA (unspec.)",
        "urn:cspace:DOMAIN:vocabularies:name(nagpracategory):item:name(subjectToNAGPRA)'subject to NAGPRA (unspec.)'"],
      ["vocabularies", "nagpraclaimtype",
        "affiliated human skeletal remains (HSR)", "urn:cspace:DOMAIN:vocabularies:name(nagpraclaimtype):item:name(affiliatedHsr)'affiliated human skeletal remains (HSR)'"],
      ["vocabularies", "nagpraclaimtype", "needs further research",
        "urn:cspace:DOMAIN:vocabularies:name(nagpraclaimtype):item:name(needsFurtherResearch)'needs further research'"],
      ["vocabularies", "nagpraclaimtype", "not subject to NAGPRA",
        "urn:cspace:DOMAIN:vocabularies:name(nagpraclaimtype):item:name(nonNagpra)'not subject to NAGPRA'"],
      ["vocabularies", "nagpraclaimtype", "object of cultural patrimony",
        "urn:cspace:DOMAIN:vocabularies:name(nagpraclaimtype):item:name(objectOfCulturalPatrimony)'object of cultural patrimony'"],
      ["vocabularies", "nagpraclaimtype", "unassociated funerary object (UFO)",
        "urn:cspace:DOMAIN:vocabularies:name(nagpraclaimtype):item:name(ufo)'unassociated funerary object (UFO)'"],
      ["vocabularies", "newsarticle", "News article",
        "urn:cspace:DOMAIN:vocabularies:name(exhibitionreferencetype):item:name(newsarticle)'News article'"],
      ["vocabularies", "osteocompleteness", "mandible only",
        "urn:cspace:DOMAIN:vocabularies:name(osteocompleteness):item:name(mandible)'mandible only'"],
      ["vocabularies", "otherpartyrole", "Preparator",
        "urn:cspace:DOMAIN:vocabularies:name(otherpartyrole):item:name(preparator)'Preparator'"],
      ["vocabularies", "otherpartyrole", "Technician",
        "urn:cspace:DOMAIN:vocabularies:name(otherpartyrole):item:name(technician)'Technician'"],
      ["vocabularies", "potsize", "1 gal. pot",
        "urn:cspace:DOMAIN:vocabularies:name(potsize):item:name(OneGalPot)'1 gal. pot'"],
      ["vocabularies", "prodpeoplerole", "designed after",
        "urn:cspace:DOMAIN:vocabularies:name(prodpeoplerole):item:name(designedAfter)'designed after'"],
      ["vocabularies", "prodpeoplerole", "traditional makers",
        "urn:cspace:DOMAIN:vocabularies:name(prodpeoplerole):item:name(traditionalMakers)'traditional makers'"],
      ["vocabularies", "propActivityType", "benlate and captan",
        "urn:cspace:DOMAIN:vocabularies:name(propActivityType):item:name(benlateAndCaptan)'benlate and captan'"],
      ["vocabularies", "propChemicals", "benlate and physan",
        "urn:cspace:DOMAIN:vocabularies:name(propChemicals):item:name(benlateAndPhysan)'benlate and physan'"],
      ["vocabularies", "propConditions", "glass cover",
        "urn:cspace:DOMAIN:vocabularies:name(propConditions):item:name(glassCover)'glass cover'"],
      ["vocabularies", "propHormones", "hormone",
        "urn:cspace:DOMAIN:vocabularies:name(propHormones):item:name(hormone)'hormone'"],
      ["vocabularies", "propPlantType", "bulbs",
        "urn:cspace:DOMAIN:vocabularies:name(propPlantType):item:name(bulbs)'bulbs'"],
      ["vocabularies", "propreason", "conservation",
        "urn:cspace:DOMAIN:vocabularies:name(propreason):item:name(conservation)'conservation'"],
      ["vocabularies", "proptype", "Division",
        "urn:cspace:DOMAIN:vocabularies:name(proptype):item:name(division)'Division'"],
      ["vocabularies", "publishto", "CollectionSpace Public Browser",
        "urn:cspace:DOMAIN:vocabularies:name(publishto):item:name(cspacepub)'CollectionSpace Public Browser'"],
      ["vocabularies", "publishto", "Culture Object",
        "urn:cspace:DOMAIN:vocabularies:name(publishto):item:name(cultureobject)'Culture Object'"],
      ["vocabularies", "publishto", "DPLA",
        "urn:cspace:DOMAIN:vocabularies:name(publishto):item:name(dpla)'DPLA'"],
      ["vocabularies", "publishto", "None",
        "urn:cspace:DOMAIN:vocabularies:name(publishto):item:name(none)'None'"],
      ["vocabularies", "publishto", "Omeka",
        "urn:cspace:DOMAIN:vocabularies:name(publishto):item:name(omeka)'Omeka'"],
      ["vocabularies", "rightsinrestriction", "Don't release owner data to third parties",
        "urn:cspace:DOMAIN:vocabularies:name(rightsinrestriction):item:name(dnr)'Don't release owner data to third parties'"],
      ["vocabularies", "scarstrat", "boiling water",
        "urn:cspace:DOMAIN:vocabularies:name(scarstrat):item:name(boilingwater)'boiling water'"],
      ["vocabularies", "scarstrat", "cold strat",
        "urn:cspace:DOMAIN:vocabularies:name(scarstrat):item:name(coldstrat)'cold strat'"],
      ["vocabularies", "taxontermflag", "invalid",
        "urn:cspace:DOMAIN:vocabularies:name(taxontermflag):item:name(invalid)'invalid'"],
      ["vocabularies", "taxontermflag", "valid",
        "urn:cspace:DOMAIN:vocabularies:name(taxontermflag):item:name(valid)'valid'"],
      ["vocabularies", "treatmentpurpose", "Exhibition",
        "urn:cspace:DOMAIN:vocabularies:name(treatmentpurpose):item:name(exhibition)'Exhibition'"],
      ["vocabularies", "trepanationcertainty", "clear evidence of trepanation",
        "urn:cspace:DOMAIN:vocabularies:name(trepanationcertainty):item:name(clear)'clear evidence of trepanation'"],
      ["vocabularies", "trepanationcertainty", "possible trepanation",
        "urn:cspace:DOMAIN:vocabularies:name(trepanationcertainty):item:name(possible)'possible trepanation'"],
      ["vocabularies", "trepanationhealing", "definite evidence for healing",
        "urn:cspace:DOMAIN:vocabularies:name(trepanationhealing):item:name(definite)'definite evidence for healing'"],
      ["vocabularies", "trepanationhealing", "no healing",
        "urn:cspace:DOMAIN:vocabularies:name(trepanationhealing):item:name(none)'no healing'"],
      ["vocabularies", "trepanationhealing", "possible healing",
        "urn:cspace:DOMAIN:vocabularies:name(trepanationhealing):item:name(possible)'possible healing'"],
      ["vocabularies", "trepanationtechnique", "grooving",
        "urn:cspace:DOMAIN:vocabularies:name(trepanationtechnique):item:name(grooving)'grooving'"],
      ["vocabularies", "uocauthorizationstatuses", "Approved",
        "urn:cspace:DOMAIN:vocabularies:name(uocauthorizationstatuses):item:name(approved)'Approved'"],
      ["vocabularies", "uoccollectiontypes", "archeology",
        "urn:cspace:DOMAIN:vocabularies:name(uoccollectiontypes):item:name(uocarcheology)'archeology'"],
      ["vocabularies", "uocmaterialtypes", "bulb",
        "urn:cspace:DOMAIN:vocabularies:name(uocmaterialtypes):item:name(bulb)'bulb'"],
      ["vocabularies", "uocmethods", "class",
        "urn:cspace:DOMAIN:vocabularies:name(uocmethods):item:name(class)'class'"],
      ["vocabularies", "uocstaffroles", "greeter",
        "urn:cspace:DOMAIN:vocabularies:name(uocstaffroles):item:name(greeter)'greeter'"],
      ["vocabularies", "uocsubcollections", "Asia",
        "urn:cspace:DOMAIN:vocabularies:name(uocsubcollections):item:name(uocsubcollection02)'Asia'"],
      ["vocabularies", "uocuserroles", "faculty",
        "urn:cspace:DOMAIN:vocabularies:name(uocuserroles):item:name(faculty)'faculty'"],
      ["vocabularies", "uocusertypes", "lecturer",
        "urn:cspace:DOMAIN:vocabularies:name(uocusertypes):item:name(lecturer)'lecturer'"],
      ["workauthorities", "work", "Makeup",
        "urn:cspace:DOMAIN:workauthorities:name(work):item:name(Makeup1608768998350)'Makeup'"]
      # rubocop:enable Layout/LineLength
    ].map { |rn| [rn[0], rn[1], rn[2], rn[3].sub(":DOMAIN:", ":c.#{domain}:")] }
  end
end
